import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className='flex flex-col h-screen text-center text-sm font-medium items-center justify-center'>
          <header className='p-4 text-center shadow-sm'>
            Central retail in VN
          </header>
          <div className='flex-grow font-medium overflow-y-auto p-4'>
            {children}
          </div>
          <footer className='p-4 shadow-sm text-center'>
            &copy; 2024 ITCare
          </footer>
        </div>

        <script
          type="text/javascript"
          src="../../node_modules/tw-elements/dist/js/tw-elements.umd.min.js"></script>
      </body>
    </html>
  )
}
